nome = str(input('Digite o seu nome: ')).strip()
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print(separa)
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))